name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup qiniu qshell environment
      uses: foxundermoon/setup-qshell@v1.0
      with:
        qshell-version: 2.4.1
    - name: login 
      run: qshell account ${{ secrets.AK }} ${{ secrets.SK }} default
    - name: upload
      run: qshell qupload2 --src-dir ./ --bucket ${{ secrets.BK }}
